name: test suite
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        run: cargo test
